### ISSUE TITLE
review

### ISSUE THREAD

**Issue by staabm** [evert/promises-and-generators#2]
just in case you are willing to spent a few minutes to fix those minor glitches. not important though.
the presentation itself is a great read/summary easy understandable for "newcomers".

slide 23: 
`In javascript it's actually 'catch' but it's a reserved keyword in javascript.`
the 2nd `javascript` should be `php`

slide 36:
more precisly `all` is a combinator function.

slide 44:
I would mention that a generator function can contain both, `yield` and `return`  (which will be available via `getReturn`[1] since php7)

[1] https://wiki.php.net/rfc/generator-return-expressions

slide 51 starts the chapter "promises and generators", but example at 52 only uses promises?

**Comment by evert** [comment]
Hey!

I made a few tweaks based on your notes. I purposely left `return` and php7 out of it. 

> slide 51 starts the chapter "promises and generators", but example at 52 only uses promises?

This is a good example of where the narrative in a set of slides gets lost a bit. It's an appropriate slide because I went back to an earlier example and then wanted to show in the next slide how it can be improved.

"You had to be there" ;)
